depend/urls.py
from django.urls import path
from .views import *

app_name='depend'
urlpatterns = [
       path('', dependantfield, name="dependantfield"),
    path('get-states/', get_states, name="get_states"),
    path('get-cities/', get_cities, name="get_cities"),
    path('get-business/', get_business, name="get_business"),
    path('get-packages/', get_package, name="get_package"),

]

myapps/urls.py
# from django import views
from django.urls import path
from . import views


app_name='myapp'
urlpatterns=[
    path ('',views.home,name='home'),
    path ('about_us/',views.about_us,name='about_us'),
    # path ('donorform/',views.Donor_Registration,name='Donor_Registration'),
    path ('contact-us/',views.contact_us,name='contact_us'),
   
    # path ('send-mail/',views.sendmail,name='send-mail'),
    path ('donor-reg-site/',views.Donor_Reg_Site,name='donor-reg-site'),
    path ('donor/<slug>/',views.donor.as_view(),name='donor_details'),
    


]

pass_r/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
       path('',include('myapps.urls')),
       path('blood-search-filter/',include('blood_search.urls')),
       path('donors/',include('donorslist.urls') ),
       path('login/',include('loginapp.urls') ),
       path('reset/password/',include('resetpassword.urls') ),
       path('depend/',include('depend.urls') ),
       path('',include('Newsfeed.urls') ),
       path('inbox/notifications',include('notifications.urls',namespace='notifications') ),
         path('', include('diseasepredictionApp.urls')),
    
]
urlpatterns+=staticfiles_urlpatterns()
if settings.DEBUG:
 urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

 urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapps/models.py
from django.db import models
from datetime import datetime,date

from django.template.defaultfilters import slugify
from django.urls import reverse
# Create your models here.
from django.contrib.auth.models import User

class Country(models.Model):
    name = models.CharField(max_length=100,null=True,blank=True)
    def __str__(self):
        return self.name

class State(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE,null=True,blank=False)
    name = models.CharField(max_length=100,null=True,blank=True)
    def __str__(self):
        return self.name

class District(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE,null=True,blank=False)
    name = models.CharField(max_length=100,null=True,blank=True)
    def __str__(self):
        return self.name
    

class Bloods_Group(models.Model):
    blood = models.CharField(max_length=100,blank=True,null=True)
    
    def __str__(self):
        return self.blood
    
    # class Meta:
    #     #jeta pore add hobe seta age dekhabe
    #     ordering=['-blood',]
        
    



class Donors_in_Site(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=124,default='username',blank=False)
    phone=models.CharField(max_length=14,null=True,blank=True) 
 
    blood = models.CharField(max_length=124,null=True,blank=False)   
    blood_donate_times=models.IntegerField(default=0,null=True,blank=True)
  
    Last_Donate=   models.CharField(max_length=11,null=True)
    image= models.ImageField(upload_to='donors_in_site',null=True,blank=True)
    country = models.CharField(max_length=124,null=True,blank=False)
   
    state = models.CharField(max_length=124,null=True,blank=False)
    
    district= models.CharField(max_length=124,null=True,blank=False)
    slug = models.SlugField(unique=True, null=True)
    created=models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.blood
    
    def get_donor_url(self):
        return reverse('myapp:donor_details',kwargs={'slug':self.slug}) #je url diye jabe tar name
       
       #slug is filter.slug jate product name e save hoy er jonno function
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug=slugify(self.user.username)
        return super().save(*args, **kwargs)
    

    age = models.IntegerField(null=True,blank=True)
    
    def getage(self):
        my_date = self.dob
        b_date = datetime.strptime(my_date, '%d/%m/%Y')
        age=int((datetime.today() - b_date).days/365)    
        age=age
        return age 

        #   today = date.today()
        # age = today.year - self.birthdate
        # if today.month < self.birthdate.month or today.month == self.birthdate.month and today.day < self.birthdate.day:
        #   age -= 1

    def month(self):

           my_date = self.dob
           mymonthmonth=int(my_date[3:5])
           todaymonth=int(date.today().strftime("%m"))
           month=abs (todaymonth-mymonthmonth)
           month=month
           return month
    
    def day(self):
           my_date = self.dob
           myday=int(my_date[:2])
           today=int(date.today().strftime("%d"))    
           day=abs (today-myday)
           return day

# Create your models here.

class Contact_us(models.Model):

    sender_name=models.CharField(max_length=100)
    from_email=models.EmailField(max_length=100)
    subject=models.CharField(max_length=100)
    message=models.TextField()
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.from_email

myapps/forms.py
from django import forms
from django.core import validators
from depend.models import Country, State, District


from django import forms
from .models import Donors_in_Site
from .fields import ListTextWidget


class DonorsDistrict(forms.ModelForm ):
    class Meta:
        model = Donors_in_Site
        fields = ['country', 'state', 'district']
        # widgets = {
        #     'country': forms.Select(attrs={'class': 'appearance-none block bg-slate-100 text-black dark:text-white border-2 border-gray-900 rounded-lg py-3 px-5 mb-3 leading-tight focus:outline-none focus:bg-white mr-[200px]'}),
        #     'state': forms.Select(attrs={'class': 'appearance-none block bg-slate-100 text-black dark:text-white border-2 border-gray-900 rounded-lg py-3 px-5 mb-3 leading-tight focus:outline-none focus:bg-white mr-[200px]'}),
        #     'district': forms.Select(attrs={'class': 'appearance-none block bg-slate-100 text-black dark:text-white border-2 border-gray-900 rounded-lg py-3 px-5 mb-3 leading-tight focus:outline-none focus:bg-white mr-[200px]'}),
        # }
        # fields = '__all__'


    def __init__(self,*args,**kwargs):
        _district_set=kwargs.pop('district_set',None)
      
        super(DonorsDistrict,self).__init__(*args,**kwargs)
        self.fields["district"].widget=ListTextWidget(data_pack=_district_set,name='district-set')

#     def __init__(self,*args,**kwargs):
#         _state_set=kwargs.pop('state_set',None)
#         super(DonorsInSiteForm,self).__init__(*args,**kwargs)
#         self.fields["state"].widget=ListTextWidget(data_list=_state_set,name='state-set')


class DonorsState(forms.ModelForm):
    class Meta:
        model = Donors_in_Site
        fields = ['country', 'state', 'district']
        # widgets = {
        #     'country': forms.Select(attrs={'class': 'appearance-none block bg-slate-100 text-black dark:text-white border-2 border-gray-900 rounded-lg py-3 px-5 mb-3 leading-tight focus:outline-none focus:bg-white mr-[200px]'}),
        #     'state': forms.Select(attrs={'class': 'appearance-none block bg-slate-100 text-black dark:text-white border-2 border-gray-900 rounded-lg py-3 px-5 mb-3 leading-tight focus:outline-none focus:bg-white mr-[200px]'}),
        #     'district': forms.Select(attrs={'class': 'appearance-none block bg-slate-100 text-black dark:text-white border-2 border-gray-900 rounded-lg py-3 px-5 mb-3 leading-tight focus:outline-none focus:bg-white mr-[200px]'}),
        # }    
    def __init__(self,*args,**kwargs):
        _state_set=kwargs.pop('state_set',None)
        super(DonorsState,self).__init__(*args,**kwargs)
        self.fields["state"].widget=ListTextWidget(data_pack=_state_set,name='state-set')


class DonorsCountry(forms.ModelForm):
    class Meta:
        model = Donors_in_Site
        fields = ['country', 'state', 'district']
        
    def __init__(self,*args,**kwargs):
        _country_set=kwargs.pop('state_set',None)
        super(DonorsCountry,self).__init__(*args,**kwargs)
        self.fields["country"].widget=ListTextWidget(data_pack=_country_set,name='country-set')

myapps/views.py
from django.shortcuts import render ,redirect,HttpResponse,HttpResponseRedirect
# from django.views.generic import ListView,DetailView

from myapps.models import  Bloods_Group,Contact_us
from django.views.generic import ListView,DetailView, TemplateView
from django.core.mail import send_mail,BadHeaderError
from django.contrib import messages
from myapps.models import Donors_in_Site
from django.core.files.storage import FileSystemStorage
from depend.models import State,Country,District
# Create your views here.

def home(request):
   return render(request,'index.html')

def about_us(request):
   return render(request,'about_us.html')

# def Donor_Registration(request):

#     countryid = request.GET.get('country')

#     stateid = request.GET.get('state')
#     state = None
#     district = None
#     if countryid :
#         getcountry = Country.objects.get(name=countryid)
        
#         state = State.objects.filter(country=getcountry)
#     if stateid:
#         getstate = State.objects.get(name=stateid)
#         district = District.objects.filter(state=getstate)
    
#     country = Country.objects.all()
#     bloods= Bloods_Group.objects.all()


#     return render(request, 'Donor_Registration1.html',locals())




def contact_us(request):
          
    if request.method=='POST':
        name= request.POST.get('name')
        email= request.POST.get('email')
        subject = request.POST.get('subject', )
        message= request.POST.get('message')
        admin='khandokarsamad4@gmail.com'
        
        if subject and message and email:
           contact=Contact_us(sender_name=name,from_email=email,subject=subject,message=message)
           contact.save()
           send_mail(subject,message,email, [admin,email,name])
           messages.success(request,'Succesfully Send Message!')
        
         
        else:
           messages.error(request,'Make sure all fields are entered and valid!')

    return render(request, 'contact.html')


def Donor_Reg_Site(request):
  print("okk")
  
  if request.method=='POST' :
    country = request.POST.get('country')
    state = request.POST.get('state')
    district = request.POST.get('district')

    if not Country.objects.filter(name=country.title()).exists():
                c=''.join(country)
                c = Country(name=c.title())
                c.save()
                # c=c.capitalize()
                # print(1111111111111111111111)
                # c=Country.objects.create(name=c)
             
                # c.save()
            
    if not State.objects.filter(name=state.title()).exists():
                c = Country.objects.get(name=country.title())
                s = State(name=state.title(), country=c)
          
                s.save()
            #    s=s.capitalize()
            #    c=c.capitalize()
            #    print(22222222222222222)
            #    c = Country.objects.get(name=c)
            #    obj = State(country=c,name=s)
         
            #    obj.save()
    if not District.objects.filter(name=district.title()).exists():
                c = State.objects.get(name=state.title())
                s = District(name=district.title(), state=c )
          
                s.save()
    #            d=''.join(district)
    #            s=''.join(state)
    #            d=d.capitalize()
    #            s=s.capitalize()
    #            obj=District.objects.create(state=s,name=d)
    #            obj=obj.capitalize()
    #            obj.save()
    try:   
        instance=Donors_in_Site.objects.get(user=request.user)
        
        if instance:
            instance.user=request.user
            phone = request.POST['phone']
            phone_str = ''.join(phone)
            instance.phone = phone_str

            blood = request.POST.get('blood'),
            blood_str = ''.join(blood)
            instance.blood=blood_str

            dob=request.POST['dob'],
            dob_str=''.join(dob)
            instance.Last_Donate = dob_str
        
            country = request.POST.get('country'),
            country_str=''.join(country)
            country_str=country_str.title()
            instance.country = country_str

            state = request.POST.get('state'),
            state_str=''.join(state)
            state_str=state_str.title()
            instance.state = state_str

            district = request.POST.get('district'),
            district_str=''.join(district)
            district_str=district_str.title()
            instance.district = district_str
        
            if len(request.FILES) == 0:
                print('no files')
            else: 
                _, file = request.FILES.popitem()
                file = file[0]
                instance.image = file
                instance.save()
        
            instance.save()
            
           
            messages.success(request,'Data has been updated!')
            return render(request, 'index.html')
    except:
        en=Donors_in_Site.objects.create(
        user=request.user,
        phone = request.POST['phone'],
        blood = request.POST.get('blood' ),
        Last_Donate = request.POST['dob'],
    
        country = request.POST.get('country').title(),
       
        state = request.POST.get('state').title(),
        district = request.POST.get('district').title()
          )
        if len(request.FILES) == 0:
            print('no files')
        else: 
            _, file = request.FILES.popitem()
            file = file[0]
            en.image = file
            en.save()

       
        print("okk")
        messages.success(request,'Data has been submitted!')
        return render(request, 'index.html')
 
        
  else:
        messages.error(request,'something mistake.please Reloade and try again!!')
        return render(request, 'dependantfield.html')
        
# Create your views here.

class donor(DetailView):
      model=Donors_in_Site
      template_name='loginapp/profile2.html'
      context_object_name='user'

myapps/templates/Donor_Registration1.html
{% extends 'base.html' %}

{% block body %}
{% load static %}
  

<!-- nav end -->

<div class="blood_search flex justify-center">
  <img class="  mr-9"  src="{% static '/images/blood_search.jpg' %}" alt="blood_search_img">
  <br>
</div>

<!-- form start here -->


<form method="POST" action="{% url 'myapp:donor-reg-site' %}" enctype="multipart/form-data">{% csrf_token %} 
  
    {% if messages %}
            {% for msg in messages %}
            <p>{{msg}}</p>
            {% endfor %}
        {% endif %}
  
 



  <div class="md:flex md:justify-between md:ml-[200px] lg:flex lg:justify-between lg:ml-[200px] xl:flex xl:justify-between xl:ml-[200px] 2xl:flex 2xl:justify-between 2xl:ml-[200px]">

    <div class="ml-5">
      <label for="dristrict" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 ">Country</label>
      <select aria-label="Default select example" id="country" required name="country" onchange="countryfield()" class="appearance-none block   bg-slate-100 text-black dark:text-white border-2 border-gray-900 rounded-lg py-3  px-5 mb-3  leading-tight focus:outline-none focus:bg-white mr-[200px]">
      
        <option selected value=""> {% if instance %} {{user.donors_in_site.country}}</option>
        {% else %}
        <option selected value="">Choose Your Country</option>{% endif %}
        {% for i in country %}
        <option name="country" value="{{i.name}}" {% if request.GET.country == i.name %}{% endif %}> {{i.name}} </option>
       
        {% endfor %}
      </select>

      </div>    

        <div class="ml-5">
          <label for="state" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 ">State</label>
          <select aria-label="Default select example" required id="state" name="state" onchange="statefield()" class="appearance-none block   bg-slate-100 text-black dark:text-white border-2 border-gray-900 rounded-lg py-3  px-5 mb-3  leading-tight focus:outline-none focus:bg-white mr-[200px]">
            <option selected value="">Choose Your State</option>
            {% for i in state %}
            <option  name="state" required value="{{i.name}}" {% if request.GET.state == i.name %}selected{% endif %}>{{i.name}}</option>
            {% endfor %}
          </select>
          </div>
        <br>
      </div>

<div class="md:flex md:justify-between md:ml-[200px] lg:flex lg:justify-between lg:ml-[200px] xl:flex xl:justify-between xl:ml-[200px] 2xl:flex 2xl:justify-between 2xl:ml-[200px]">
  <div class="ml-5">
    <label for="district" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 ">District</label>
    <select required  aria-label="Default select example" id="district" name="district" class="appearance-none block   bg-slate-100 text-black dark:text-white border-2 border-gray-900 rounded-lg py-3  px-5 mb-3  leading-tight focus:outline-none focus:bg-white mr-[200px]">
      <option selected value="">Choose Your District</option>
    
  {% for i in district %}
      <option name="district" value="{{i.name}}">{{i.name}}</option>
  {% endfor %}
    </select>
    </div>


   

      <div class="ml-5">
        <label for="blood" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 ">Blood</label>
        <select aria-label="Default select example" id="blood" name="blood" required class="appearance-none block   bg-slate-100 text-black dark:text-white border-2 border-gray-900 rounded-lg py-3  px-5 mb-3  leading-tight focus:outline-none focus:bg-white mr-[190px] ">
          <option selected value="" >Choose Your Blood</option>
          {% for j in bloods %}
          <option name= "blood"  value="{{j.blood}}" {% if request.GET.blood == j.id|lower %}selected{% endif %}> {{j.blood}} </option>   
          {% endfor %}  
        </select>
        </div>


      <br>
    </div>


  <div class="md:flex md:justify-between md:ml-[200px] lg:flex lg:justify-between lg:ml-[200px] xl:flex xl:justify-between xl:ml-[100px] 2xl:flex 2xl:justify-between 2xl:ml-[200px]">
    <div class="xl:ml-[130px]">
      <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 mr-1 ml-3" for="grid-first-name">
        Full Name
      </label>
      <input class="appearance-none block  bg-slate-100 text-black dark:text-white border-2 border-gray-900 rounded-lg py-3 px-4 ml-3 leading-tight focus:outline-none focus:bg-blue focus:border-gray-500  placeholder-gray-500 dark:placeholder-text-white" name="name" id="grid-first-name" required type="text" placeholder="Jane">
    </div>
   <br>

    <div class="xl:mr-[240px] ">
      <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 " for="grid-last-phone">
        Phone Number
      </label>
      <input type="tel" id="phone" name="phone"  minlength="12" maxlength="14"class=" appearance-none block bg-slate-100 text-black dark:text-white border-2 border-gray-900 rounded-lg py-3 mr-1 leading-tight focus:outline-none focus:bg-blue focus:border-gray-500 placeholder-mr[120px] dark:placeholder-text-white"  placeholder="phone number" required>

    </div>
 
  </div>
  <br>
  <!-- name phone end -->

  <!-- blood photo start -->
  <div class="xl:flex xl:justify-center xl:gap-[220px] xl:mr-[40px] xl:pt-1 md:flex md:justiify-center md:ml-[8px]">


    <div class="">
        <label class=" block uppercase  tracking-wide  border-red-500 rounded text-gray-700 text-xs font-bold mb-1 ml-1 " name='image' for="grid-last-name">
          image
        </label>
      
        <input name="image" id="image" type="file" class="mt-1 border-2 border-gray-900 rounded-lg " aria-describedby="file_input_help" >
      </div> 
 
      <div class="pb-3"> 
      <label class=" mr-3  ml-[45px] block uppercase tracking-wide text-gray-700 text-xs font-bold  " for="grid-last-name" >
       Last Donate
      </label>
    
      <input  datepicker  type="text" name="dob"   class=" ml-[45px] appearance-none block bg-slate-100 text-black dark:text-white border-2 border-gray-900 rounded-lg py-3   mb-3 leading-tight focus:outline-none focus:bg-white  " placeholder="Birth Date">
    </div> 

  </div>

  <div class="flex items-start justify-center">
    <div class="flex items-center h-5">
      <input id="terms" aria-describedby="terms" type="checkbox" class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600 dark:ring-offset-gray-800" required="">
    </div>
    <div class="ml-3 text-sm">
      <label for="terms" class="font-light text-gray-500 dark:text-gray-300"> <span class="text-font">You are 18 or more years</span> I accept the <a class="font-medium text-primary-600 hover:underline dark:text-primary-500" href="#">Terms and Conditions</a></label>
    </div>
</div>


<div class="flex justify-center">
  
  <button class=" mt-[70px] bg-gray-900  dark:bg-black  border-2 border-red-500 hover:border-green-500 rounded-lg hover:bg-gray-900 text-white dark:text-white font-semibold py-2 px-4 shadow">
    SAVE
  </button>
</div>
</form>

<br>

  <!-- footer start here -->
  <script>
    function countryfield(){
        countryid = document.getElementById('country').value;
        window.location = "/donorform/?country="+countryid;
    }
    document.getElementById('country').addEventListener('change', function(event) {
      event.preventDefault();
    });
    function statefield(){
       stateid = document.getElementById('state').value;
       window.location = "/donorform/?country="+'{{request.GET.country}}'+"&state="+stateid;
    }
  </script>
{% endblock body %}

myapps/templates/contact.html
{% extends 'base.html' %}

{% block body %}
{% load static %}
  

<!-- navbar ends here -->

<!-- contact start -->
<section class="text-gray-600 body-font ">
  <div class="blood_search flex justify-center">
    <img class="  mr-9"  src="{% static '/images/contact_us.png' %}" alt="blood_search_img">
  </div>
    <br>
    {% if messages %}
{% for msg in messages %}
<p class="flex justify-center text-green-500 font-bold ">{{msg}}</p>
{% endfor %}

{% endif %}
<div class="container px-5 py-24 flex sm:flex-nowrap ">
  <div
      class="lg:w-2/3 md:w-1/2 bg-gray-300 rounded-lg overflow-hidden sm:mr-10 p-10 flex items-end justify-start relative">
      <iframe width="100%" height="100%" class="absolute inset-0" frameborder="0" title="map" marginheight="0"
          marginwidth="0" scrolling="no"
          src="https://maps.google.com/maps?width=100%&height=600&hl=en&q=%C4%B0zmir+(My%20Business%20Name)&ie=UTF8&t=&z=14&iwloc=B&output=embed"
          style="filter: grayscale(1) contrast(1.2) opacity(0.4);"></iframe>
      <div class="bg-white relative flex flex-wrap py-6 rounded shadow-md">
          <div class="lg:w-1/2 px-6">
              <h2 class="title-font font-semibold text-gray-900 tracking-widest text-xs">ADDRESS</h2>
              <p class="mt-1">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iusto ea itaque adipisci
                  blanditiis voluptatum perspiciatis quam soluta ipsam quia dolore optio illum iste beatae officia
                  autem omnis fugiat, quod vel.</p>
          </div>
          <div class="lg:w-1/2 px-6 mt-4 lg:mt-0">
              <h2 class="title-font font-semibold text-gray-900 tracking-widest text-xs">EMAIL</h2>
              <a class="text-indigo-500 leading-relaxed">khandokarsamad4@@gmail.com</a>
              <h2 class="title-font font-semibold text-gray-900 tracking-widest text-xs mt-4">PHONE</h2>
              <p class="leading-relaxed">123-456-7890</p>
          </div>
      </div>
  </div>
  <div class="lg:w-1/3 md:w-1/2 bg-white flex flex-col md:ml-auto w-full md:py-8 mt-8 md:mt-0 border rounded-2 rounded-lg shadow-xl mr-2 px-2">
      <h1 class="text-gray-900 text-xl mb-1 font-bold mb-4 title-font">Feedback</h1>
      <p class="leading-relaxed mb-5 text-gray-600">Post-ironic portland shabby chic echo park, banjo fashion axe
      </p>
      <form method="POST" action="">{% csrf_token %}
      <div class=" mb-4">
          <label for="name" class="leading-7 text-sm text-gray-600">Name</label>
          <input type="text" id="name" name="name"
              class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
      </div>
      <div class=" mb-4">
          <label for="email" class="leading-7 text-sm text-gray-600">Email</label>
          <input type="email" id="email" name="email"
              class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
      </div>
      <div class=" mb-4">
        <label for="subject" class="leading-7 text-sm text-gray-600">Subject</label>
        <input type="text" id="subject" name="subject"
            class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
    </div>
      <div class=" mb-4">
          <label for="message" class="leading-7 text-sm text-gray-600">Message</label>
          <textarea id="message" name="message"
              class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out"></textarea>
      </div>
      <button
          class="text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">SEND</button>
      </form>
          <p class="text-xs text-gray-500 mt-3">Chicharrones blog helvetica normcore iceland tousled brook viral
          artisan.</p>
  </div>
</div>
</section>>

  <!-- contact ends here -->


  <!-- footer start here -->

  

{% endblock body %}